within ThermalIntegrationLibrary.ProductionEquipment.Ovens.Test;
function Test_AnnealingOven_Function

algorithm
simulateModel("ThermalIntegrationLib.ProductionEquipment.Ovens.Test.Test_AnnealingOven", stopTime=10000, method="Cvode", resultFile="Test_AnnealingOven") annotation(__Dymola_interactive=true);

 // Script generated by Dymola Thu Nov  4 11:11:08 2021
// Plot commands
removePlots(false);
createPlot(id=1, position={0, 0, 1573, 607}, y={"EiB_AnnealingOven_v1_1.processController.TargetTemperature.y","EiB_AnnealingOven_v1_1.T_retort.T"}, range={0.0, 10000.0, 200.0, 800.0}, grid=true, legends={"Soll-Temperatur (K)", "Ist-Temperatur (K)"}, colors={{28,108,200}, {238,46,47}}, displayUnits={"K", "K"},timeUnit="h");
createPlot(id=1, position={0, 0, 1573, 607}, y={"EiB_AnnealingOven_v1_1.electricDemand[1].Power[1]"}, range={0.0, 10000.0, -500000.0, 1000000.0}, grid=true, legends={"Hauptanschluss (P_el, W)"}, subPlot=102, colors={{28,108,200}}, displayUnits={"W"},timeUnit="h");
createPlot(id=1, position={0, 0, 1573, 607}, y={"EiB_AnnealingOven_v1_1.coolDemand[3].Q_flow[1]", "EiB_AnnealingOven_v1_1.dissipationFlowRate"}, range={0.0, 10000.0, -2000000.0, 4000000.0}, grid=true, legends={"Kühlwasserbedarf zentral (P_th, W)", "Abwärme konvektiv (P_th, W)"}, subPlot=103, colors={{28,108,200}, {238,46,47}}, displayUnits={"W", "W"},timeUnit="h");

end Test_AnnealingOven_Function;
