within ThermalIntegrationLibrary.ProductionEquipment.CleaningMachines;
package CabinetCleaningMachine
  extends ThermalIntegrationLibrary.BaseClasses.Icons.CleaningMachines;
end CabinetCleaningMachine;
