within ThermalIntegrationLib.ProductionEquipment.MachineTools.Test;
function Validation_TurningMachine_Function

algorithm
  simulateModel("ThermalIntegrationLib.ProductionEquipment.MachineTools.Test.Validation_TurningMachine", stopTime=30000, outputInterval=10, method="Cvode", resultFile="Validation_EiB_MachineTool") annotation(__Dymola_interactive=true);

// Script generated by Dymola Tue Nov  2 11:03:41 2021
// Plot commands
removePlots(false);
createPlot(id=1, position={0, 0, 1573, 767}, y={"data.y[5]", "EiB_MachineTool_v1_1.thermalSystem.coldWater.Q_flow"}, range={0.0, 30000.0, 0.0, 1500.0}, grid=true, legends={"cold Water demand (measurement)", ""}, colors={{28,108,200}, {238,46,47}}, displayUnits={"", "W"});
createPlot(id=1, position={0, 0, 1573, 767}, y={"data.y[2]", "EiB_MachineTool_v1_1.AC_DC.y"}, range={0.0, 30000.0, 0.0, 6000.0}, grid=true, legends={"main connection (measurement)", ""}, subPlot=102, colors={{238,46,47}, {28,108,200}}, displayUnits={"", "W"});
createPlot(id=1, position={0, 0, 1573, 767}, y={"EiB_MachineTool_v1_1.processController.OperatingMode"}, range={0.0, 30000.0, 0.0, 6.0}, grid=true, subPlot=103, colors={{28,108,200}});

end Validation_TurningMachine_Function;
