within ThermalIntegrationLib.ProductionEquipment.CleaningMachines;
package EiB_CleaningMachine1Tank_thermal
  extends ThermalIntegrationLib.BaseClasses.Icons.CleaningMachines;
end EiB_CleaningMachine1Tank_thermal;
